import { ServiceError } from '@/data/errors'

export async function {{MAIN_NAME}}(): Promise<any> {
    try {
        const result: any = await {}

        return result
    } catch (error: unknown) {
        throw new ServiceError({{MAIN_NAME}}.name, error)
    }
}
